name : oui mais c'est quoi le service ???

on :
  workflow_dispatch:

jobs:
  checkNginx:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 4242:80
    steps:
      - name: curl nginx page and print response code
        run: curl -s -o /dev/null -w "%{http_code}" http://localhost:4242
