name : oui mais c'est quoi le service ???

on :
  workflow_dispatch:

jobs:
  checkNginx:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 4242:80
    steps:
      - name: curl nginx page
        run: curl http://localhost:4242 | grep "HTTP/"
