name : oui mais c'est quoi le service ???

on :
  workflow_dispatch:

jobs:
  checkNginx:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 4242:80
    steps:
      - name: Afficher la version de nginx
        run: curl http://localhost:4242
