name : HelloWorld!

on :
  issues :
    types : [ opened, edited, closed ]
  pull_request :
    types : [ opened, edited ]
  gollum :
    types : [ created, edited, deleted ]
  schedule :
    - cron :  ' 0 0 1 * * '
  workflow_dispatch:

jobs :
  build :
    runs-on :  ubuntu-latest
    steps :
      - uses: actions/checkout@v3

      - name: c'est l'heure de t'acheter une montre !
        run: echo "Hello, world! Today is $(date +'%m-%d-%Y %H:%M:%S')"
