name : HelloWorld!

on :
  issues :
    types : [ opened, edited, closed ]
  pull_request :
    types : [ opened, edited ]
  gollum :
    types : [ created, edited, deleted ]
  schedule :
    - cron :  ' 0 0 1 * * '

jobs :
  build :
    runs-on :  ubuntu-latest
  steps :
    - uses: actions/checkout@v3

    - name :  HelloWorld!
      run :  echo  " Hello, world! The time is $(date)."
