name : rompiche quel os c'est ??? Mystere !!
on :
  workflow_dispatch:

jobs:
  buildUbuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher la version de l'OS (ubuntu)
        run: cat /etc/os-release
  buildWindows:
    runs-on: windows-latest
    steps:
      - name: Afficher la version de l'OS (Windows)
        run: Get-ComputerInfo -Property "*version"
  buildMac:
    runs-on: macos-latest
    steps:
      - name: Afficher la version de l'OS (Mac)
        run: sw_vers
  AlpContainerVer:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Afficher la version de l'OS (container alpine)
        run: cat /etc/os-release
  CentOsContainerVer:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - name: Afficher la version de l'OS (container centos)
        run: cat /etc/os-release
  FedoraContainerVer:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Afficher la version de l'OS (container fedora)
        run: cat /etc/os-release
  