name : rompiche quel os c'est ??? Mystere !!
on :
  workflow_dispatch:

jobs :
  build :
    runs-on : [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Afficher le nom de l'OS
        run: echo "${{ runner.os }}"
