name : uuuuuuuuuuuuuuuuuh
on :
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sort
        run: ls -1 files | sort > sorted.txt && cat sorted.txt
